server:
  port: 8090

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 100MB
  cloud:
    gateway:
      httpclient:
        max-initial-line-length: 65536
        max-header-size: 65536
        max-chunk-size: 65536
      discovery:
        locator:
          enabled: true
      routes:
        - id: document-service
          uri: lb://DOCUMENT-SERVICE
          predicates:
            - Path=/api/files/**
          filters:
            - name: CircuitBreaker
              args:
                name: filestorageCB
                fallbackUri: forward:/fallback/filestorage

        - id: signature-verify
          uri: lb://SIGNATURE-SERVICE
          predicates:
            - Path=/signatures/verify
          filters:

        - id: signature-service
          uri: lb://SIGNATURE-SERVICE
          predicates:
            - Path=/signatures/**
          filters:
            - name: CircuitBreaker
              args:
                name: signatureCB
                fallbackUri: forward:/fallback/signature

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCB
                fallbackUri: forward:/fallback/user

        - id: template-service
          uri: lb://TEMPLATE-SERVICE
          predicates:
            - Path=/api/templates/**
          filters:
            - name: CircuitBreaker
              args:
                name: templateCB
                fallbackUri: forward:/fallback/template

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationCB
                fallbackUri: forward:/fallback/notification


resilience4j:
  circuitbreaker:
    instances:
      filestorageCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      signatureCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      userCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      templateCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      notificationCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

management:
  endpoints:
    web:
      exposure:
        include: resilience4j.circuitbreakers, health

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true