server:
  port: 8090

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 100MB
  cloud:
    gateway:
      httpclient:
        max-initial-line-length: 65536
        max-header-size: 65536
        max-chunk-size: 65536
      discovery:
        locator:
          enabled: true
      routes:
        ####################### documents #########################
        # without circuit breaker because of multipart upload
        - id: document-upload
          uri: lb://DOCUMENT-SERVICE
          predicates:
            - Path=/documents
          filters:
            - StripPrefix=0

        # without circuit breaker
        - id: document-template-upload
          uri: lb://DOCUMENT-SERVICE
          predicates:
            - Path=/documents/template
          filters:
            - StripPrefix=0

        # with circuit breaker
        - id: document-service
          uri: lb://DOCUMENT-SERVICE
          predicates:
            - Path=/documents/**
          filters:
            - name: CircuitBreaker
              args:
                name: filestorageCB
                fallbackUri: forward:/fallback/filestorage
            - StripPrefix=0

        ####################### signatures #########################
        # without circuit breaker
        - id: signature-verify
          uri: lb://SIGNATURE-SERVICE
          predicates:
            - Path=/signatures/verify
          filters:
            - StripPrefix=0

        # with circuit breaker
        - id: signature-service
          uri: lb://SIGNATURE-SERVICE
          predicates:
            - Path=/signatures/**
          filters:
            - name: CircuitBreaker
              args:
                name: signatureCB
                fallbackUri: forward:/fallback/signature
            - StripPrefix=0

        ####################### USERS #########################
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**, /api/profile/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCB
                fallbackUri: forward:/fallback/user
            - StripPrefix=0

        ####################### TEMPLATES #########################
        # without circuit breaker
        - id: template-upload
          uri: lb://TEMPLATE-SERVICE
          predicates:
            - Path=/templates
          filters:
            - StripPrefix=0

        # with circuit breaker
        - id: template-service
          uri: lb://TEMPLATE-SERVICE
          predicates:
            - Path=/templates/**
          filters:
            - name: CircuitBreaker
              args:
                name: templateCB
                fallbackUri: forward:/fallback/template
            - StripPrefix=0

        ####################### NOTIFICATIONS #########################
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationCB
                fallbackUri: forward:/fallback/notification
            - StripPrefix=0

resilience4j:
  circuitbreaker:
    instances:
      filestorageCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      signatureCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      userCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      templateCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      notificationCB:
        slidingWindowSize: 5
        minimumNumberOfCalls:
