server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: document-service
          uri: lb://DOCUMENT-SERVICE
          predicates:
            - Path=/files/**

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /users/v3/api-docs
      - name: document-service
        url: /files/v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: true



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true