server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/documentsUsersRealm

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

keycloak:
  server-url: http://localhost:8080
  realm: documentsUsersRealm
  client-id: documents-flow-client
  client-secret: rHwwJzOPsmaE4ORWac9lTKAEiH8GiQmA
  admin-user: admin
  admin-password: admin


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true