server:
  port: 8083

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/documentsUsersRealm
  data:
    mongodb:
      uri: mongodb://localhost:27017/signaturedb
      auto-index-creation: true


document:
  service:
    url: http://localhost:8082