server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/templates
  application:
    name: TEMPLATE-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true